CREATE DATABASE IF NOT EXISTS codesmic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE codesmic;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  institution VARCHAR(100) NOT NULL,
  join_date VARCHAR(50) NOT NULL,
  xp INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 1,
  challenges_completed INT NOT NULL DEFAULT 0,
  projects_completed INT NOT NULL DEFAULT 0,
  rank VARCHAR(100) NOT NULL DEFAULT 'Rookie Star'
);

CREATE TABLE IF NOT EXISTS activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  xp INT NOT NULL DEFAULT 0,
  type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  xp INT NOT NULL DEFAULT 10,
  subject VARCHAR(100) NOT NULL,
  subtopic VARCHAR(100) NOT NULL,
  difficulty VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'Fix & Run Lab',
  mini_materi TEXT NOT NULL,
  code_html TEXT NOT NULL,
  code_css TEXT NOT NULL,
  code_js TEXT NOT NULL,
  task TEXT NOT NULL,
  validation_js TEXT NOT NULL,
  hint1 TEXT NOT NULL,
  hint2 TEXT NOT NULL,
  hint3 TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO questions (title, xp, subject, subtopic, difficulty, type, mini_materi, code_html, code_css, code_js, task, validation_js, hint1, hint2, hint3)
VALUES
  -- Fix & Run Lab (3 soal)
  (
    'Judul Halaman Dasar',
    10,
    'HTML',
    'Struktur Dasar HTML',
    'Mudah',
    'Fix & Run Lab',
    'HTML halaman dasar memerlukan DOCTYPE, elemen html, head, title, dan body.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title></title>\n</head>\n<body>\n  \n</body>\n</html>',
    '',
    '',
    'Lengkapi tag <title> sehingga teks halaman menjadi "Belajar Web".',
    'const title = document.querySelector("title");\nreturn !!title && title.innerText.trim() === "Belajar Web";',
    'Cek tag <title> di dalam elemen <head>.',
    'Nama halaman biasanya ditulis di dalam <title>.',
    'Gunakan document.querySelector("title").innerText untuk mengisi nama halaman.'
  ),
  (
    'Buat Tombol CTA',
    10,
    'HTML',
    'Struktur Layout & Semantic',
    'Mudah',
    'Fix & Run Lab',
    'Belajar membuat tombol call-to-action sederhana menggunakan HTML dan kelas.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>CTA Demo</title>\n</head>\n<body>\n  <div class="cta-container">\n    <button id="cta-button"></button>\n  </div>\n</body>\n</html>',
    '',
    '',
    'Isi teks tombol dengan "Mulai Belajar" dan pastikan tombol memiliki id cta-button.',
    'const button = document.querySelector("#cta-button");\nreturn !!button && button.innerText.trim() === "Mulai Belajar";',
    'Cari elemen dengan id cta-button.',
    'Periksa innerText tombol.',
    'Gunakan document.querySelector("#cta-button").innerText untuk mengecek teks tombol.'
  ),
  (
    'Style Form Input',
    15,
    'CSS',
    'Form Styling',
    'Mudah',
    'Fix & Run Lab',
    'Styling form input dengan border, padding, dan font size yang sesuai.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Form</title>\n</head>\n<body>\n  <form>\n    <input type="text" class="form-input" placeholder="Nama">\n  </form>\n</body>\n</html>',
    '.form-input {\n  /* Tambahkan styling di sini */\n}',
    '',
    'Tambahkan border 2px solid #333, padding 10px, dan font-size 16px ke class form-input.',
    'const input = document.querySelector(".form-input");\nconst styles = window.getComputedStyle(input);\nreturn styles.borderWidth === "2px" && styles.padding === "10px";',
    'Gunakan border property untuk membuat border.',
    'Padding adalah space di dalam elemen.',
    'Cek computed styles dengan window.getComputedStyle().'
  ),
  -- Code Challenge Arena (4 soal)
  (
    'Buat Card Layout',
    20,
    'HTML/CSS',
    'Grid & Flexbox',
    'Sedang',
    'Code Challenge Arena',
    'Membuat layout card responsif menggunakan CSS Grid atau Flexbox.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Card Layout</title>\n</head>\n<body>\n  <div class="card-container">\n    <div class="card">Card 1</div>\n    <div class="card">Card 2</div>\n    <div class="card">Card 3</div>\n  </div>\n</body>\n</html>',
    '.card-container {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));\n  gap: 20px;\n}\n\n.card {\n  background: #f0f0f0;\n  padding: 20px;\n  border-radius: 8px;\n  box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n}',
    '',
    'Buat layout card yang responsif menggunakan CSS Grid dengan minimal 3 kartu.',
    'const container = document.querySelector(".card-container");\nconst cards = container.querySelectorAll(".card");\nreturn cards.length >= 3;',
    'Gunakan CSS Grid untuk membuat layout.',
    'grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)) membuat layout responsif.',
    'Setiap card harus memiliki class .card.'
  ),
  (
    'Navbar dengan Navigation',
    25,
    'HTML/CSS',
    'Navigation Patterns',
    'Sedang',
    'Code Challenge Arena',
    'Membuat navbar dengan link navigasi dan styling yang menarik.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Navbar</title>\n</head>\n<body>\n  <nav class="navbar">\n    <div class="logo">MyApp</div>\n    <ul class="nav-links">\n      <li><a href="#">Home</a></li>\n      <li><a href="#">About</a></li>\n      <li><a href="#">Contact</a></li>\n    </ul>\n  </nav>\n  <main>Content</main>\n</body>\n</html>',
    '.navbar {\n  display: flex;\n  justify-content: space-between;\n  align-items: center;\n  background: #333;\n  padding: 1rem 2rem;\n}\n\n.logo {\n  color: white;\n  font-weight: bold;\n  font-size: 1.5rem;\n}\n\n.nav-links {\n  display: flex;\n  list-style: none;\n  gap: 2rem;\n}\n\n.nav-links a {\n  color: white;\n  text-decoration: none;\n}',
    '',
    'Buat navbar dengan logo dan navigation links yang tersusun horizontal.',
    'const navbar = document.querySelector(".navbar");\nconst logo = navbar.querySelector(".logo");\nconst links = navbar.querySelectorAll(".nav-links a");\nreturn !!logo && links.length >= 3;',
    'Gunakan flexbox untuk layout navbar.',
    'Logo harus ada di kiri dan links di kanan.',
    'Gunakan justify-content: space-between untuk memisahkan logo dan links.'
  ),
  (
    'Tombol dengan Hover Effect',
    20,
    'CSS',
    'Interactive Elements',
    'Sedang',
    'Code Challenge Arena',
    'Membuat tombol dengan efek hover yang halus dan menarik.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Buttons</title>\n</head>\n<body>\n  <button class="btn">Klik Saya</button>\n</body>\n</html>',
    '.btn {\n  padding: 12px 24px;\n  font-size: 16px;\n  background: #007bff;\n  color: white;\n  border: none;\n  border-radius: 4px;\n  cursor: pointer;\n  transition: all 0.3s ease;\n}\n\n.btn:hover {\n  background: #0056b3;\n  transform: translateY(-2px);\n  box-shadow: 0 4px 12px rgba(0,86,179,0.4);\n}',
    '',
    'Tambahkan efek hover dengan perubahan warna, shadow, dan transform.',
    'const btn = document.querySelector(".btn");\nconst styles = window.getComputedStyle(btn);\nreturn styles.transition.includes("all");',
    'Gunakan :hover pseudo-class untuk efek mouse over.',
    'Gunakan transition untuk membuat perubahan smooth.',
    'transform: translateY(-2px) membuat tombol naik saat hover.'
  ),
  (
    'Modal Dialog',
    30,
    'HTML/CSS/JS',
    'Modal Components',
    'Sulit',
    'Code Challenge Arena',
    'Membuat modal dialog yang bisa dibuka dan ditutup dengan JavaScript.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Modal</title>\n</head>\n<body>\n  <button class="open-modal">Buka Modal</button>\n  \n  <div class="modal" style="display: none;">\n    <div class="modal-content">\n      <span class="close">&times;</span>\n      <p>Ini adalah modal dialog!</p>\n    </div>\n  </div>\n</body>\n</html>',
    '.modal {\n  position: fixed;\n  z-index: 1;\n  left: 0;\n  top: 0;\n  width: 100%;\n  height: 100%;\n  background-color: rgba(0,0,0,0.4);\n}\n\n.modal-content {\n  background-color: #fefefe;\n  margin: 15% auto;\n  padding: 20px;\n  border: 1px solid #888;\n  width: 80%;\n  max-width: 500px;\n}\n\n.close {\n  color: #aaa;\n  float: right;\n  font-size: 28px;\n  font-weight: bold;\n  cursor: pointer;\n}',
    'const openBtn = document.querySelector(".open-modal");\nconst modal = document.querySelector(".modal");\nconst closeBtn = document.querySelector(".close");\n\nopenBtn.addEventListener("click", () => {\n  modal.style.display = "block";\n});\n\ncloseBtn.addEventListener("click", () => {\n  modal.style.display = "none";\n});',
    'Implementasikan modal yang bisa dibuka dengan tombol dan ditutup dengan X.',
    'const modal = document.querySelector(".modal");\nreturn modal !== null && modal.style.display !== "none" || modal.style.display === "block";',
    'Gunakan display: none/block untuk show/hide modal.',
    'Tambahkan click event listener ke tombol.',
    'Modal-content harus di tengah dengan margin: 15% auto.'
  ),
  -- Debugging Zone (3 soal)
  (
    'Fix Layout Broken',
    25,
    'CSS',
    'Flexbox Debugging',
    'Sedang',
    'Debugging Zone',
    'Identifikasi dan perbaiki layout yang rusak akibat CSS error.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Broken Layout</title>\n</head>\n<body>\n  <div class="container">\n    <div class="item">Item 1</div>\n    <div class="item">Item 2</div>\n    <div class="item">Item 3</div>\n  </div>\n</body>\n</html>',
    '.container {\n  display: flex;\n  flex-direction: column;\n  /* ERROR: gap tidak ada, items tertumpuk */\n}\n\n.item {\n  background: #e0e0e0;\n  padding: 10px;\n}',
    '',
    'Identifikasi error CSS yang menyebabkan layout tertumpuk. Tambahkan gap: 10px ke container.',
    'const container = document.querySelector(".container");\nconst styles = window.getComputedStyle(container);\nreturn styles.gap === "10px";',
    'Layout items tertumpuk berarti ada yang kurang dari flexbox.',
    'Cek apakah ada gap property.',
    'Gunakan getComputedStyle untuk cek CSS yang applied.'
  ),
  (
    'Debug Console Error',
    20,
    'JavaScript',
    'Error Handling',
    'Mudah',
    'Debugging Zone',
    'Cari dan perbaiki error di console JavaScript.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Debug</title>\n</head>\n<body>\n  <p id="text">Hello</p>\n  <button id="btn">Click</button>\n</body>\n</html>',
    '',
    'const btn = document.querySelector("#butn"); // TYPO: "butn" instead of "btn"\nbtn.addEventListener("click", () => {\n  document.querySelector("#text").innerText = "Clicked";\n});',
    'Cari error: element dengan id "butn" tidak ada (harusnya "btn"). Perbaiki typo tersebut.',
    'const btn = document.querySelector("#btn");\nreturn btn !== null && btn.id === "btn";',
    'Error biasanya di console browser.',
    'Periksa apakah ID selector sesuai dengan HTML.',
    'Gunakan querySelector dengan ID yang benar.'
  ),
  (
    'Fix Event Listener',
    25,
    'JavaScript',
    'Event Handling',
    'Sedang',
    'Debugging Zone',
    'Perbaiki event listener yang tidak bekerja dengan benar.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>Event Debug</title>\n</head>\n<body>\n  <input type="text" class="input-field">\n  <p class="output">Result: </p>\n</body>\n</html>',
    '',
    'const input = document.querySelector(".input-field");\nconst output = document.querySelector(".output");\n\n// ERROR: addEventListener dijalankan pada elemen yang tidak ada\ninput.addEventListener("input", (e) => {\n  output.innerText = "Result: " + e.target.value;\n});',
    'Pastikan event listener diberikan pada elemen yang tepat dan event type benar (input untuk text field).',
    'const input = document.querySelector(".input-field");\nreturn input !== null && input instanceof HTMLInputElement;',
    'Cek apakah elemen dengan class input-field ada.',
    'Event "input" adalah event untuk perubahan nilai input.',
    'Gunakan console.log untuk debug event listener.'
  ),
  -- Mini Project Builder (3 soal)
  (
    'Portfolio Landing Page Part 1: Header',
    50,
    'HTML/CSS',
    'Portfolio Projects',
    'Sedang',
    'Mini Project Builder',
    'Bangun portfolio landing page step by step. Bagian 1: Buat header dengan hero section.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>My Portfolio</title>\n</head>\n<body>\n  <!-- Buat header dengan logo dan navigation di sini -->\n  <!-- Buat hero section dengan judul dan deskripsi -->\n</body>\n</html>',
    'body {\n  margin: 0;\n  font-family: "Segoe UI", Tahoma, Geneva, Verdana, sans-serif;\n}\n\nheader {\n  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\n  color: white;\n  padding: 2rem;\n}\n\nheader h1 {\n  margin: 0;\n  font-size: 2.5rem;\n}\n\n.hero {\n  padding: 4rem 2rem;\n  text-align: center;\n}',
    '',
    'Buat header dengan logo/nama dan navigation bar. Tambahkan hero section dengan judul "Welcome to My Portfolio" dan deskripsi singkat.',
    'const header = document.querySelector("header");\nconst hero = document.querySelector(".hero");\nreturn !!header && !!hero;',
    'Header harus ada dengan background color yang menarik.',
    'Hero section harus memiliki class .hero dan text "Welcome".',
    'Gunakan semantic HTML: <header>, <nav>, <h1>.'
  ),
  (
    'Portfolio Landing Page Part 2: Projects Section',
    50,
    'HTML/CSS',
    'Portfolio Projects',
    'Sedang',
    'Mini Project Builder',
    'Lanjutkan portfolio. Bagian 2: Buat projects showcase dengan card grid.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>My Portfolio</title>\n</head>\n<body>\n  <!-- Header dari part 1 -->\n  \n  <!-- Buat section projects dengan grid layout -->\n  <!-- Setiap project adalah card dengan gambar, judul, deskripsi -->\n</body>\n</html>',
    '/* Style dari part 1 */\n\n.projects-section {\n  padding: 4rem 2rem;\n  background: #f8f9fa;\n}\n\n.projects-grid {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));\n  gap: 2rem;\n  max-width: 1200px;\n  margin: 0 auto;\n}\n\n.project-card {\n  background: white;\n  border-radius: 8px;\n  overflow: hidden;\n  box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n  transition: transform 0.3s;\n}\n\n.project-card:hover {\n  transform: translateY(-8px);\n}',
    '',
    'Buat section projects dengan minimal 3 project cards di grid layout. Setiap card harus punya judul dan deskripsi project.',
    'const section = document.querySelector(".projects-section");\nconst cards = document.querySelectorAll(".project-card");\nreturn !!section && cards.length >= 3;',
    'Gunakan grid-template-columns untuk responsive layout.',
    'Setiap project card harus memiliki class .project-card.',
    'Tambahkan hover effect dengan transform: translateY().'
  ),
  (
    'Portfolio Landing Page Part 3: Contact & Footer',
    50,
    'HTML/CSS/JS',
    'Portfolio Projects',
    'Sulit',
    'Mini Project Builder',
    'Selesaikan portfolio. Bagian 3: Buat contact form dan footer.',
    '<!DOCTYPE html>\n<html>\n<head>\n  <title>My Portfolio</title>\n</head>\n<body>\n  <!-- Header dan Projects dari part 1 & 2 -->\n  \n  <!-- Buat contact section dengan form -->\n  <!-- Buat footer dengan links dan copyright -->\n</body>\n</html>',
    '/* Style dari part 1 & 2 */\n\n.contact-section {\n  padding: 4rem 2rem;\n  max-width: 600px;\n  margin: 0 auto;\n}\n\n.contact-form {\n  display: flex;\n  flex-direction: column;\n  gap: 1rem;\n}\n\n.contact-form input,\n.contact-form textarea {\n  padding: 0.75rem;\n  border: 1px solid #ddd;\n  border-radius: 4px;\n  font-family: inherit;\n}\n\nfooter {\n  background: #333;\n  color: white;\n  text-align: center;\n  padding: 2rem;\n}',
    'const form = document.querySelector(".contact-form");\nconst input = form.querySelector("input");\nconst textarea = form.querySelector("textarea");\ninput.value = "Test";\nreturn input.value === "Test" && !!textarea;',
    'Buat contact form dengan input fields: nama, email, pesan.',
    'Contact form harus ada dengan input dan textarea.',
    'Footer harus memiliki copyright text dan social media links.'
  );
